[target.'cfg(target_arch = "riscv32")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[env]
ESP_LOG = "info"
